package parku30.mapslt

object MapsltClassifiers {

  val KategorijosMap = Map(
    20->"Muziejus, ekspozicija",
    201->"Archeologinis paveldas",
    202->"Architektūros paveldas",
    203->"Gamtinis paveldas",
    204->"Geologinė vertybė",
    205->"Hidrografinė vertybė",
    206->"Inžinerinis paveldas",
    207->"Istorinis paveldas",
    208->"Urbanistikos vertybė",
    209->"Kūrėjų darbai, amatininkas",
    210->"Mitologinis objektas",
    211->"Paminklas",
    213->"Apžvalgos aikštelė",
    214->"Paukščių stebėjimo vieta",
    217->"Stovėjimo aikštelė",
    221->"Jachtklubas",
    223->"Kempingas",
    224->"Kaimo turizmo sodyba",
    226->"Informacinis stendas",
    228->"Poilsiavietė, stovyklavietė, laužavietė",
    229->"Poilsio bazė",
    219->"Žirgynas",
    230->"Paplūdimys",
    227->"Parko administracija",
    231->"Girininkija",
    232->"Pramogų parkas",
    233->"Parkas",
    234->"Sporto centras",
    236->"Turizmo paslaugos",
    235->"Dailės galerija",
    237->"Nardymo centras",
    238->"Lankytojų centras",
    239->"Poilsio, laisvalaikio centras",
    240->"Vandens transporto nuoma",
    241->"Dviračių nuoma",
    14->"Maldos namai, sakralinis paveldas",
    8->"Autobusų stotis",
    9->"Geležinkelio stotis",
    12->"Kavinė, baras, restoranas",
    13->"Turizmo informacijos centras",
    15->"Viešbučiai, apgyvendinimo paslaugos"
  )


  val SavivaldybesMap = Map(
    11->"Alytaus m. sav.",
    12->"Birštono sav.",
    13->"Vilniaus m. sav.",
    15->"Druskininkų sav.",
    18->"Marijampolės sav.",
    19->"Kauno m. sav.",
    21->"Klaipėdos m. sav.",
    23->"Neringos sav.",
    25->"Palangos m. sav.",
    27->"Panevėžio m. sav.",
    29->"Šiaulių m. sav.",
    30->"Visagino sav.",
    32->"Akmenės r. sav.",
    33->"Alytaus r. sav.",
    34->"Anykščių r. sav.",
    36->"Biržų r. sav.",
    38->"Varėnos r. sav.",
    39->"Vilkaviškio r. sav.",
    41->"Vilniaus r. sav.",
    42->"Elektrėnų sav.",
    43->"Zarasų r. sav.",
    45->"Ignalinos r. sav.",
    46->"Jonavos r. sav.",
    47->"Joniškio r. sav.",
    48->"Kalvarijos sav.",
    49->"Kaišiadorių r. sav.",
    52->"Kauno r. sav.",
    53->"Kėdainių r. sav.",
    54->"Kelmės r. sav.",
    55->"Klaipėdos r. sav.",
    56->"Kretingos r. sav.",
    57->"Kupiškio r. sav.",
    58->"Kazlų Rūdos sav.",
    59->"Lazdijų r. sav.",
    61->"Mažeikių r. sav.",
    62->"Molėtų r. sav.",
    63->"Pagėgių sav.",
    65->"Pakruojo r. sav.",
    66->"Panevėžio r. sav.",
    67->"Pasvalio r. sav.",
    68->"Plungės r. sav.",
    69->"Prienų r. sav.",
    71->"Radviliškio r. sav.",
    72->"Raseinių r. sav.",
    73->"Rokiškio r. sav.",
    74->"Rietavo sav.",
    75->"Skuodo r. sav.",
    77->"Tauragės r. sav.",
    78->"Telšių r. sav.",
    79->"Trakų r. sav.",
    81->"Ukmergės r. sav.",
    82->"Utenos r. sav.",
    84->"Šakių r. sav.",
    85->"Šalčininkų r. sav.",
    86->"Švenčionių r. sav.",
    87->"Šilalės r. sav.",
    88->"Šilutės r. sav.",
    89->"Širvintų r. sav.",
    91->"Šiaulių r. sav.",
    94->"Jurbarko r. sav."
  )

}
